server:
  port: 8066
spring:
  application:
    name: yyd
  redis:
    port: 6379
    host: 123.249.41.142
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.249.41.142:3306/yyd?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://123.249.41.142:27017/yyd
      username: root
      password: 123456

mybatis-plus:
  mapper-locations: classpath*:/com/yyd/yyd/mapper/**/*.xml
  global-config:
    db-config:
      table-prefix: tb_   # 表名前缀
      id-type: auto   # id策略为自增长
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.yyd.yyd.models.enums.**
logging:
  config: src/main/resources/logback.xml
  level:
    com.hl.magic: trace

#swagger:
#  base-package: 'com.yyd.yyd'
#  base-path: '/**'
#  title: '注解方式的Swagger'
#  description: '这是注解方式的Swagger'
#  version: '2.0'
#  license-url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
#  license: 'The Apache License'
#  contact:
#    name: 'yyd'
#    url: 'https:www.baidu.com'
#    email: '116217017@qq.com'


#nacos:
# config:
#   server-addr: 123.249.41.142:8848
# discovery:
#   server-addr: 123.249.41.142:8848


